name: Ajout à la Roadmap

on:
  issues:
    types: [opened, reopened, transferred]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/Yannick101984/projects/2
          github-token: ${{ secrets.GH_PAT }}
